#!/usr/bin/env sh

set -e

# Uploads data on Deblan.
#
# $1: Source code
# $2: Language (can be empty)
# $3: Title (can be empty)
paste() {
    code=$1; shift
    language=$1; shift
    title=$1; shift

    curl \
        -ksS \
        -o /dev/null \
        -w "%{http_code} %{redirect_url}" \
        --data-urlencode code="$code" \
        --data-urlencode language="$language" \
        --data-urlencode title="$title" \
        "https://wall.deblan.org/"
}

# Gets an offset of a space separated string.
#
# $1: Offset
# $2: String
offset() {
    offset=$1; shift
    string=$1; shift

    echo "$string" | cut -d " " -f "$offset"
}

# $1: Input file
# $2: Language (optional)
# $3: Title (optional)
main() {
    file=$1; shift
    language=$1
    title=$2

    if [ "$file" = - ]; then
        file=/dev/stdin
    elif [ ! -f "$file" ]; then
        echo "Invalid file." >&2
        exit 1
    fi

    code=$(cat "$file")
    response=$(paste "$code" "$language" "$title")
    http_code=$(offset 1 "$response")
    redirect_url=$(offset 2 "$response")

    if [ -z "$redirect_url" ]; then
        echo "An error occurred, got $http_code response code." >&2
        exit 2
    fi

    echo "$redirect_url"
}

main "$@"
