#!/usr/bin/env sh

# Uploads data on Deblan.
#
# $1: Source code
# $2: Language
# $3: Title
paste() {
    local code=$1; shift
    local language=$1; shift
    local title=$1; shift

    curl \
        --data-urlencode code="$code" \
        --data-urlencode language="$language" \
        --data-urlencode title="$title" \
        -o /dev/null \
        -s \
        -w "%{http_code} %{redirect_url}" \
        "https://wall.deblan.org/"
}

# Gets an offset of a space separated string.
#
# $1: Offset
# $2: String
offset() {
    local -i offset=$1; shift
    local string=$1; shift

    cut -d " " -f "$offset" <<< "$data"
}

# $1: Input file
# $2: Language
# $3: Title
main() {
    local file=$1; shift
    local language=$1; shift
    local title=$1; shift

    if [ "$file" == - ]; then
        file=/dev/stdin
    elif [ ! -f "$file" ]; then
        echo "Invalid file." >&2
        exit 1
    fi

    local code=$(cat "$file")
    local response=$(paste "$code" "$language" "$title")
    local http_code=$(offset 1 "$response")
    local redirect_url=$(offset 2 "$response")

    if [ -z "$redirect_url" ]; then
        echo "An error occurred, got $http_code response code." >&2
        exit 2
    fi

    echo "$redirect_url"
}

main "$@"
