#!/bin/sh -e
#
# Usage: dwall [options] [<file>]
#
# Arguments:
#   <file>  File to upload, `stdin` by default.
#
# Options:
#   -h, --help                 Show this screen.
#   -l, --language <language>  Programming language of the uploaded file.
#   -t, --title <title>        Title of the paste.
#

readonly PROGFILE=$0

help() {
    sed -nr '1,2d;/^#/!q;s/^# ?//p' < "$PROGFILE"
}

# Upload on Deblan.
#
# $1: Source code
# $2: Language (can be empty)
# $3: Title (can be empty)
paste() {
    code=$1; shift
    language=$1; shift
    title=$1; shift

    curl \
        -sS \
        -o /dev/null \
        -w "%{http_code} %{redirect_url}" \
        --data-urlencode code="$code" \
        --data-urlencode language="$language" \
        --data-urlencode title="$title" \
        --data-urlencode line=1 \
        "https://wall.deblan.org/"
}

# Get an offset of a space separated string.
#
# $1: Offset
# $2: String
offset() {
    offset=$1; shift
    string=$1; shift

    echo "$string" | cut -d " " -f "$offset"
}

# $1: Input file
# $2: Language (optional)
# $3: Title (optional)
main() {
    language=
    title=

    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help) help; exit ;;
            -l|--language) language=$2; shift 2 ;;
            -t|--title) title=$2; shift 2 ;;
            -*) echo "Unknown option: $1" >&2; exit 1 ;;
        esac
    done

    file=${1:-/dev/stdin}

    if [ ! -e "$file" ]; then
        echo "Invalid file: $file" >&2
        exit 2
    fi

    code=$(cat "$file")
    response=$(paste "$code" "$language" "$title")
    http_code=$(offset 1 "$response")
    redirect_url=$(offset 2 "$response")

    if [ -z "$redirect_url" ]; then
        echo "An error occurred, got $http_code response code." >&2
        exit 3
    fi

    echo "$redirect_url"
}

main "$@"
